// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Обменик валют",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Обменик валют",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.-------------",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sandwich),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/CoreOffice/CoreXLSX.git", "0.14.2"..<"1.0.0"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk", "11.5.0"..<"12.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CoreXLSX", package: "corexlsx")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)